# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Custom prompt format
#format = '''
#[╭ ]()sudhan in $directory
#[╰ ]()$character'''
format = '''$character $directory[: ]()'''

[character]
success_symbol = '[λ](bold green)' # On successful command execution
error_symbol = '[✘](bold red)' # On faulty command execution

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
