########### LOGIN TEXT ###########
cat ~/.config/ASCII/butthead.txt
#ls ~/.config/ASCII | sort -R 


########### ALIASES ###########
alias python="python3"

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(starship init zsh)"
